sudo: required
services: docker
language: python
cache: pip
branches:
    only:
        - master
        - build
env:
    matrix:
        include:
            - python: "2.7"
              env: PYPICONTENTSRANGE="0"
            - python: "2.7"
              env: PYPICONTENTSRANGE="1"
            - python: "2.7"
              env: PYPICONTENTSRANGE="2"
            - python: "2.7"
              env: PYPICONTENTSRANGE="3"
            - python: "2.7"
              env: PYPICONTENTSRANGE="4"
            - python: "2.7"
              env: PYPICONTENTSRANGE="5"
            - python: "2.7"
              env: PYPICONTENTSRANGE="6"
            - python: "2.7"
              env: PYPICONTENTSRANGE="7"
            - python: "2.7"
              env: PYPICONTENTSRANGE="8"
            - python: "2.7"
              env: PYPICONTENTSRANGE="9"
            - python: "2.7"
              env: PYPICONTENTSRANGE="a"
            - python: "2.7"
              env: PYPICONTENTSRANGE="b"
            - python: "2.7"
              env: PYPICONTENTSRANGE="c"
            - python: "2.7"
              env: PYPICONTENTSRANGE="d"
            - python: "2.7"
              env: PYPICONTENTSRANGE="e"
            - python: "2.7"
              env: PYPICONTENTSRANGE="f"
            - python: "2.7"
              env: PYPICONTENTSRANGE="g"
            - python: "2.7"
              env: PYPICONTENTSRANGE="h"
            - python: "2.7"
              env: PYPICONTENTSRANGE="i"
            - python: "2.7"
              env: PYPICONTENTSRANGE="j"
            - python: "2.7"
              env: PYPICONTENTSRANGE="k"
            - python: "2.7"
              env: PYPICONTENTSRANGE="l"
            - python: "2.7"
              env: PYPICONTENTSRANGE="m"
            - python: "2.7"
              env: PYPICONTENTSRANGE="n"
            - python: "2.7"
              env: PYPICONTENTSRANGE="o"
            - python: "2.7"
              env: PYPICONTENTSRANGE="p"
            - python: "2.7"
              env: PYPICONTENTSRANGE="q"
            - python: "2.7"
              env: PYPICONTENTSRANGE="r"
            - python: "2.7"
              env: PYPICONTENTSRANGE="s"
            - python: "2.7"
              env: PYPICONTENTSRANGE="t"
            - python: "2.7"
              env: PYPICONTENTSRANGE="u"
            - python: "2.7"
              env: PYPICONTENTSRANGE="v"
            - python: "2.7"
              env: PYPICONTENTSRANGE="w"
            - python: "2.7"
              env: PYPICONTENTSRANGE="x"
            - python: "2.7"
              env: PYPICONTENTSRANGE="y"
            - python: "2.7"
              env: PYPICONTENTSRANGE="z"
            - python: "2.7"
              env: PYPICONTENTSRANGE="z"
            - python: "2.6"
              env: STDLIBCONTENTS="2.6"
            - python: "2.7"
              env: STDLIBCONTENTS="2.7"
            - python: "3.2"
              env: STDLIBCONTENTS="3.2"
            - python: "3.3"
              env: STDLIBCONTENTS="3.3"
            - python: "3.4"
              env: STDLIBCONTENTS="3.4"
            - python: "3.5"
              env: STDLIBCONTENTS="3.5"
    global:
        - GITUSERNAME="Luis Alejandro Martínez Faneyth"
        - GITUSERMAIL="luis@huntingbears.com.ve"
        - GHREPO="https://github.com/LuisAlejandro/pypicontents"
        - secure: "TIOeJ/QSHzNENPTyDs2Sezh8BAFCinqvIQzYekGuDPfSXPspMflNSqY7/AZ6XOUgFLo8MEk1RlUlyYGo0GiYnX+254At1W0vRwFr6Hxp/RBrG18AcV6O334P7g81GYwitFp/VKp5JFMrs2vXUfLk352RToiFTlI5KOUwNQqLY8RpqxB20MiAOLynraXHIiZW4s97FcoZChO/Kj4sAvwvMaLrBcq3jb6Tu2uR6XH/7r5pxOH+MDIqlkmxZK58KKMg1YBEbqVjWXYDfWmDAQNZu0uMF4Rjs2R++tfZXz5Z0a0icGIwjRTNsaSuYNRorUMJEkVLmTT1HhPaMsHlLYYJCxSkUe4wk91OOOP45WoLlCisBYVKnWLyJeV6QEKrx3YV3RvEmVmmIpnTQUse1n2XCNenTTTv/3g05BxBq7qMO2O0i7x7Q3LGh2+H1sBBAALwiny8k82esKiKwiETkpaR0VWjZvn6pcRl7F8BAM5z/cFTs+FELf1vazLopXWuTExHdWug5wlmGheS0/cgZjkoexCuEzV5YWK/C2/xAwRyZlpHxTNVNjw1xCB2fVTE6G/VpZ51HKxSzhEO1pFcQr/N2IbcHy9HxOfgGdtwp7Mawr3pOOwVcMu6CzwR2SeIqJ62ftSPzU1zXWW2fNO4++saADKUTydaLfGAMWmIywIPu0k="
before_script: ./before_script.sh
script: ./script.sh
after_success: ./after_success.sh
