sudo: required
services: docker
dist: trusty
group: edge
language: python
matrix:
    include:
        - python: "2.6"
          env: TOXENV=py26
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.2"
          env: TOXENV=py32
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
install:
    - pip install -r requirements-dev.txt
script:
    - tox -e ${TOXENV}
    - |
        docker run -v ${PWD}:${PWD} -w ${PWD} \
            dockershelf/python:${TRAVIS_PYTHON_VERSION} bash -c \
            "python${TRAVIS_PYTHON_VERSION} setup.py install && \
            pypicontents pypi -o data/0-9/pypi.json -f logs/0-9/pypi.log -R 0-9"
    - |
        docker run -v ${PWD}:${PWD} -w ${PWD} \
            dockershelf/python:${TRAVIS_PYTHON_VERSION} bash -c \
            "python${TRAVIS_PYTHON_VERSION} setup.py install && \
            pypicontents stdlib -o stdlib/${TRAVIS_PYTHON_VERSION}/stdlib.json"
after_success:
    - coveralls
