sudo: required
services: docker
language: python
cache: pip
python: 2.7
env:
    matrix:
        - PYPICONTENTSRANGE="0-9"
        - PYPICONTENTSRANGE="a"
        - PYPICONTENTSRANGE="b"
        - PYPICONTENTSRANGE="c"
        - PYPICONTENTSRANGE="d"
        - PYPICONTENTSRANGE="e"
        - PYPICONTENTSRANGE="f"
        - PYPICONTENTSRANGE="g"
        - PYPICONTENTSRANGE="h"
        - PYPICONTENTSRANGE="i"
        - PYPICONTENTSRANGE="j"
        - PYPICONTENTSRANGE="k"
        - PYPICONTENTSRANGE="l"
        - PYPICONTENTSRANGE="m"
        - PYPICONTENTSRANGE="n"
        - PYPICONTENTSRANGE="o"
        - PYPICONTENTSRANGE="p"
        - PYPICONTENTSRANGE="q"
        - PYPICONTENTSRANGE="r"
        - PYPICONTENTSRANGE="s"
        - PYPICONTENTSRANGE="t"
        - PYPICONTENTSRANGE="u"
        - PYPICONTENTSRANGE="v"
        - PYPICONTENTSRANGE="w"
        - PYPICONTENTSRANGE="x"
        - PYPICONTENTSRANGE="y"
        - PYPICONTENTSRANGE="z"
    global:
        - GITUSERNAME="PyPIContents Bot"
        - GITUSERMAIL="luis@huntingbears.com.ve"
        - GHREPO="https://github.com/LuisAlejandro/pypicontents"
        - secure: PKeUMQDxsnkHQJi81leTdU/u1a0YhCvvV7UGUwTVOrnjZQ7uQzX/h2bEe85DpdzMtFdStxeLK+cNvyAYZPfjxn+3x4bl/z0baX0VePARshNdukopAyohHjsLNdtVcO1SY1WrQiFQsI9kelR38P3P9OaFpFds1mZusTTOM9eAyw8xnNWU7JBBGsDCjujMJCYhrsc4EgyzFd/DgypjPUb/duardWXfxv2YUD4MT6bSDscEH9FySZQCu90HDdyDBWuoJ+tNiIB5lKeJJpfhwciImnTCvK9gBEPnhcHceaWmllb4nDKoYjAQq4kOS+/zEGLYqrw11eGtBOuxwuUJGwCYM//wFbTx3IjxrFm+YPba47pXqfIa7Nj3ZewjFmmCMNP4ZHv2fTdzQ7rJukRUefesMNcdBT/1YNNuZKsRl6pqq3/qTUmFEDuSnUGYsLVIJbLBiz2X1bc8ieVdOUVX6OdfvipYQ9mbvzIbkMr9E02MeXUaxdBmiYSlwkxyPCGcwwWue6yaXESbniqUaq2XstBUblItaklH/MdBkVSto09uIr5JvILx0ZCaEo3GXvBxDDlxyO1BlLiwBS66msGsWPmLPIGiXNoMfb/tJhTUvxGM+oVgnEHTbIOjL8JMa9WO97O3HbkpxCtSQslPEZ1FkHSWvlTm/A86wh3n1EJhHIWThCk=
before_script:
    - git fetch origin contents:contents
    - git checkout master
    - git checkout contents data
    - git checkout contents logs
script:
    - mkdir -p logs/${PYPICONTENTSRANGE}
    - docker pull luisalejandro/python:sid
    - docker run -v ${PWD}:${PWD} -v ${HOME}/.cache/pip:/root/.cache/pip -w ${PWD} -e PYPICONTENTSRANGE=${PYPICONTENTSRANGE} luisalejandro/python:sid python main.py | tee logs/${PYPICONTENTSRANGE}/contents.log
after_success:
    - git config --global user.name "${GITUSERNAME}"
    - git config --global user.email "${GITUSERMAIL}"
    - git add --all .
    - git commit -a -m "[ci skip]"
    - git checkout contents
    - git pull origin contents
    - git checkout master data
    - git checkout master logs
    - git add --all .
    - git commit -a -m "[ci skip] Updating PyPIContents index through Travis cron jobs."
    - git push -q "https://${GHTOKEN}@${GHREPO#*//}" contents > /dev/null 2>&1
