sudo: required
services: docker
dist: trusty
group: edge
language: python
python: 2.7
cache: pip
branches:
    only:
        - master
        - build
env:
    global:
        - GITUSERNAME="Luis Alejandro Martínez Faneyth"
        - GITUSERMAIL="luis@huntingbears.com.ve"
        - GHREPO="https://github.com/LuisAlejandro/pypicontents"
        - secure: "TIOeJ/QSHzNENPTyDs2Sezh8BAFCinqvIQzYekGuDPfSXPspMflNSqY7/AZ6XOUgFLo8MEk1RlUlyYGo0GiYnX+254At1W0vRwFr6Hxp/RBrG18AcV6O334P7g81GYwitFp/VKp5JFMrs2vXUfLk352RToiFTlI5KOUwNQqLY8RpqxB20MiAOLynraXHIiZW4s97FcoZChO/Kj4sAvwvMaLrBcq3jb6Tu2uR6XH/7r5pxOH+MDIqlkmxZK58KKMg1YBEbqVjWXYDfWmDAQNZu0uMF4Rjs2R++tfZXz5Z0a0icGIwjRTNsaSuYNRorUMJEkVLmTT1HhPaMsHlLYYJCxSkUe4wk91OOOP45WoLlCisBYVKnWLyJeV6QEKrx3YV3RvEmVmmIpnTQUse1n2XCNenTTTv/3g05BxBq7qMO2O0i7x7Q3LGh2+H1sBBAALwiny8k82esKiKwiETkpaR0VWjZvn6pcRl7F8BAM5z/cFTs+FELf1vazLopXWuTExHdWug5wlmGheS0/cgZjkoexCuEzV5YWK/C2/xAwRyZlpHxTNVNjw1xCB2fVTE6G/VpZ51HKxSzhEO1pFcQr/N2IbcHy9HxOfgGdtwp7Mawr3pOOwVcMu6CzwR2SeIqJ62ftSPzU1zXWW2fNO4++saADKUTydaLfGAMWmIywIPu0k="
    matrix:
          - PYPICONTENTSRANGE="0"
          - PYPICONTENTSRANGE="1"
          - PYPICONTENTSRANGE="2"
          - PYPICONTENTSRANGE="3"
          - PYPICONTENTSRANGE="4"
          - PYPICONTENTSRANGE="5"
          - PYPICONTENTSRANGE="6"
          - PYPICONTENTSRANGE="7"
          - PYPICONTENTSRANGE="8"
          - PYPICONTENTSRANGE="9"
          - PYPICONTENTSRANGE="a"
          - PYPICONTENTSRANGE="b"
          - PYPICONTENTSRANGE="c"
          - PYPICONTENTSRANGE="d"
          - PYPICONTENTSRANGE="e"
          - PYPICONTENTSRANGE="f"
          - PYPICONTENTSRANGE="g"
          - PYPICONTENTSRANGE="h"
          - PYPICONTENTSRANGE="i"
          - PYPICONTENTSRANGE="j"
          - PYPICONTENTSRANGE="k"
          - PYPICONTENTSRANGE="l"
          - PYPICONTENTSRANGE="m"
          - PYPICONTENTSRANGE="n"
          - PYPICONTENTSRANGE="o"
          - PYPICONTENTSRANGE="p"
          - PYPICONTENTSRANGE="q"
          - PYPICONTENTSRANGE="r"
          - PYPICONTENTSRANGE="s"
          - PYPICONTENTSRANGE="t"
          - PYPICONTENTSRANGE="u"
          - PYPICONTENTSRANGE="v"
          - PYPICONTENTSRANGE="w"
          - PYPICONTENTSRANGE="x"
          - PYPICONTENTSRANGE="y"
          - PYPICONTENTSRANGE="z"
          - PYPICONTENTSRANGE="z"
          - STDLIBCONTENTS="2.6"
          - STDLIBCONTENTS="2.7"
          - STDLIBCONTENTS="3.2"
          - STDLIBCONTENTS="3.4"
          - STDLIBCONTENTS="3.5"
          - STDLIBCONTENTS="3.6"
before_script:
    - |
        if [ -n "${PYPICONTENTSRANGE}" ]; then
            git fetch origin contents:contents
            git checkout master
            git checkout contents data/${PYPICONTENTSRANGE}/pypi.json logs/${PYPICONTENTSRANGE}/pypi.log
        fi

        if [ -n "${STDLIBCONTENTS}" ]; then
            git fetch origin contents:contents
            git checkout master
            git checkout contents stdlib/${STDLIBCONTENTS}/stdlib.json
        fi
script:
    - |
        sudo chown -R ${USER}:${USER} . ${HOME}/.cache/pip

        if [ -n "${PYPICONTENTSRANGE}" ]; then
            docker run -v ${PWD}:${PWD} -v ${HOME}/.cache/pip:/root/.cache/pip \
                -w ${PWD} luisalejandro/pypicontents:2.7 pypirazzi process \
                    -o data/${PYPICONTENTSRANGE}/pypi.json \
                    -f logs/${PYPICONTENTSRANGE}/pypi.log \
                    -R ${PYPICONTENTSRANGE} -L 3M -M 2G -T 2100
        fi

        sudo chown -R ${USER}:${USER} . ${HOME}/.cache/pip

        if [ -n "${STDLIBCONTENTS}" ]; then
            docker run -v ${PWD}:${PWD} -w ${PWD} \
                luisalejandro/pypicontents:${STDLIBCONTENTS} pypirazzi stdlib \
                    -o stdlib/${STDLIBCONTENTS}/stdlib.json \
                    -p ${STDLIBCONTENTS}
        fi
after_success:
    - |
        if [ -n "${PYPICONTENTSRANGE}" ]; then
            git checkout master
            git config --global user.name "${GITUSERNAME}"
            git config --global user.email "${GITUSERMAIL}"
            git add data/${PYPICONTENTSRANGE}/pypi.json logs/${PYPICONTENTSRANGE}/pypi.log
            git commit -m "[ci skip]" data/${PYPICONTENTSRANGE}/pypi.json logs/${PYPICONTENTSRANGE}/pypi.log
            git reset --hard
            git clean -fxd
            git checkout contents
            git pull origin contents
            git checkout master data/${PYPICONTENTSRANGE}/pypi.json logs/${PYPICONTENTSRANGE}/pypi.log
            git add data/${PYPICONTENTSRANGE}/pypi.json logs/${PYPICONTENTSRANGE}/pypi.log
            git commit -m "[ci skip] Updating PyPIContents index (letter ${PYPICONTENTSRANGE})." \
                data/${PYPICONTENTSRANGE}/pypi.json logs/${PYPICONTENTSRANGE}/pypi.log
            git push -q "https://${GHTOKEN}@${GHREPO#*//}" contents > /dev/null 2>&1
        fi


        if [ -n "${STDLIBCONTENTS}" ]; then
            git checkout master
            git config --global user.name "${GITUSERNAME}"
            git config --global user.email "${GITUSERMAIL}"
            git add stdlib/${STDLIBCONTENTS}/stdlib.json
            git commit -m "[ci skip]" stdlib/${STDLIBCONTENTS}/stdlib.json
            git reset --hard
            git clean -fxd
            git checkout contents
            git pull origin contents
            git checkout master stdlib/${STDLIBCONTENTS}/stdlib.json
            git add stdlib/${STDLIBCONTENTS}/stdlib.json
            git commit -m "[ci skip] Updating stdlib index (version ${STDLIBCONTENTS})." \
                stdlib/${STDLIBCONTENTS}/stdlib.json
            git push -q "https://${GHTOKEN}@${GHREPO#*//}" contents > /dev/null 2>&1
        fi